### PR TITLE
:globe_with_meridians: Translate plugin base

### PR DESCRIPTION
**Pull request by patou**
Add translation of the plugin.

### CODE REVIEW

**Comment by patou** [comment]
Hello @caiyucong,
I begin to translate also the plugin, can you complete the translation to chinese ?
And after is the translation works for you, in my test the french translation not displayed.

**Comment by caiyucong** [comment]
> Hello @caiyucong, I begin to translate also the plugin, can you complete the translation to chinese ? And after is the translation works for you, in my test the french translation not displayed.

ok

**Comment by caiyucong** [comment]
> Hello @caiyucong, I begin to translate also the plugin, can you complete the translation to chinese ? And after is the translation works for you, in my test the french translation not displayed.

In my testing, Chinese characters were not displayed properly until I added the 'Chinese (Simplified) Language Pack / 中文语言包' plugin. 

Perhaps you also need to add the corresponding French language pack.

**Comment by patou** [comment]
> > Hello @caiyucong, I begin to translate also the plugin, can you complete the translation to chinese ? And after is the translation works for you, in my test the french translation not displayed.
> 
> In my testing, Chinese characters were not displayed properly until I added the 'Chinese (Simplified) Language Pack / 中文语言包' plugin. 
> 
> Perhaps you also need to add the corresponding French language pack.

Ok it's work for chinese.
For French, there are no Language Pack.

**Pull request merged**
