### PR TITLE
Migrate to new IntelliJ Gradle Plugin

### PR DESCRIPTION
**Pull request by DeKaN**
The first step for #92

### CODE REVIEW

**Comment by patou** [comment]
> The first step for #92

Thanks, you followed the guide migration ?
https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html

**Comment by DeKaN** [comment]
Yes, I did

**Comment by DeKaN** [comment]
@patou Looks like Qodana should be updated, but I'm not sure - can't see its logs

**Comment by patou** [comment]
Thanks, I finish the corrections in this PR : https://github.com/patou/gitmoji-intellij-plugin/pull/96

**Comment by pboling** [comment]
Will this result in the setting of "use unicode" being saved with the other plugin's settings in the JetBrains cloud, so they sync across projects?

**Comment by patou** [comment]
Thanks @DeKaN for your help, the new version is now live.

**Comment by pboling** [comment]
@patou Will this result in the setting of "use unicode" being saved with the other plugin's settings in the JetBrains cloud, so they sync across projects?

**Pull request closed without merging**
